Students controller
pejath/university pull request #2
Opened 2022-02-02 12:23 UTC by pejath

All veiws for Students controller

2022-02-02 20:55 UTC, msterjanov requested changes
Хорошая работа! Молодец, что разработал views. Но есть некоторые моменты по контроллеру, которые необходимо исправить.

2022-02-02 20:55 UTC, msterjanov commented on app/controllers/students_controller.rb
> +class StudentsController < ApplicationController
Думаю, что ещё стоит добавить **index** эндпоинт. Который будет содержать сразу всех студентов. 

Можешь попробовать в этом эндпоинте сделать сразу функционал фильтрации данных. 
Для это тебе в параметрах будут приходить поля вида { "group_id" => 1 }. И если такой параметр придет, то ты будешь возвращать студентов только определенной группы.

2022-02-02 20:55 UTC, msterjanov commented on app/controllers/students_controller.rb
> +  def show
Если тело метода пустое, то лучше записать метод так:
```
def show; end
```

2022-02-02 20:55 UTC, msterjanov commented on app/controllers/students_controller.rb
> +    @students = Student.new
Почему переменная названа во множественном числе?

2022-02-02 20:55 UTC, msterjanov commented on app/controllers/students_controller.rb
> +  def edit
То же самое, что и для `show`

2022-02-02 20:55 UTC, msterjanov commented on app/controllers/students_controller.rb
> +    @students.save
- Переменная во множественном числе
- Что будет, если произойдет ошибка валидации? Нужно сделать обработку ошибки и уведомить пользователя, что что-то пошло не так и студент не был создан

2022-02-02 20:55 UTC, msterjanov commented on app/controllers/students_controller.rb
> +    @students.update(student_params)
Что будет, если произойдет ошибка валидации? Нужно сделать обработку ошибки и уведомить пользователя, что что-то пошло не так и студент не был обновлен

2022-02-02 20:55 UTC, msterjanov commented on app/controllers/students_controller.rb
> +  end
Думаю, что этот эндпоинт не нужен. Эту функциональность можно реализовать в `index` с помощью фильтрации. Например, ты будешь возвращать студентов только с красными дипломами если в параметрах пришло `{ "redDiplomas" => true }`

2022-02-02 20:55 UTC, msterjanov commented on app/controllers/students_controller.rb
> +  end
Этот метод тоже не нужен. Его функцию будет выполнять эндпоинт `index`

2022-02-02 20:55 UTC, msterjanov commented on app/controllers/students_controller.rb
> +    @students = Student.find(params[:id])
Думаю, что из-за этой переменной, всё во множественном числе. Сделай ее в единственном числе.

2022-02-02 20:55 UTC, msterjanov commented on app/helpers/students_helper.rb
> +module StudentsHelper
Этот хелпер тебе как раз и поможет для вынесения логики фильтрации из контроллера.
Сделай тут метод `filter_by_params(scope, params)`. Этот метод будет фильтровать данные на основании переменной `params`. В качестве `scope` будешь передавать `Student.all`. 
Потом добавь этот хелпер к своему контроллеру.

2022-02-02 20:55 UTC, msterjanov commented on config/routes.rb
> +  get '/journal/(:group)', to: 'students#journal'
Круто, что ты разобрался, как делать эндпоинт с параметром. Но думаю, что нам не нужны эти два endpoint. Они не отвечают требованиям _REST_. Поэтому их нужно удалить

2022-02-02 20:55 UTC, msterjanov commented on config/routes.rb
> +  resources :students, only: %i[destroy create new edit show update], path: 'student'
Здесь ещё нужен *index* . И зачем ты делаешь `path: student`? Пусть остается `students`, как по умолчанию

2022-02-03 18:09 UTC, IvanChibisov requested changes
Нужно сделать ещё пару изменения для фильтрации и обработки ошибок.

Сразу же в этом ПР можешь сделать перехват ошибки ActiveRecord::RecordNotFound. Чтобы вместо 500 ошибки сервера слать в ответ 404 и перенаправлять на эту страницу

2022-02-03 18:09 UTC, IvanChibisov commented on app/helpers/students_helper.rb
> +    if params.key?(:group_id)
- Когда я говорил про красные дипломы, я имел ввиду добавление их внутрь `filter_by_params`.
- Также не обязательно проверять params на наличие ключа group_id. Если такого ключа не будет просто вернется nil.
- Вообще params это будет hash вида `{ group_id: 1, redDiplomas: true }`. Поэтому можно проитерировать по хешу и фильтровать сразу и по группе и reqDiplomas. Что-то вроде этого:
```
params.each do |key, value|
  next if value.blank?

  scope = if key.to_s == 'group_id'
             scope.where(group_id: value)
          elsif key.to_s == 'redDiplomas'
             scope.red_diplomas
          else
            scope
          end
end
```

2022-02-03 18:09 UTC, IvanChibisov commented on app/controllers/students_controller.rb
> +
Тут сделай filter_params метод:
```
def filter_params
  params.require(:filter).permit(:group_id, :redDiplomas)
end
```
И в index будешь вызывать `@students = filter_by_params(Student.all, filter_params)`

2022-02-03 18:09 UTC, IvanChibisov commented on app/controllers/students_controller.rb
> +      format.html { redirect_to student_url, notice: "Student was successfully destroyed." }
Тут нужно отловить тоже возможную ошибку. Сделай это как в update: 
`if @student.destroy` destroy метод возвращает true или false

2022-02-05 08:58 UTC, msterjanov approved these changes

2022-02-05 09:02 UTC, IvanChibisov approved these changes
Всё отлично, сделай ещё маленький фикс и мержи этот ПР в мастер ветку

2022-02-05 15:26 UTC, merged