Facuties and department
pejath/university pull request #6
Opened 2022-02-10 10:25 UTC by pejath

2022-02-11 14:56 UTC, IvanChibisov requested changes

2022-02-11 14:56 UTC, IvanChibisov commented on app/controllers/departments_controller.rb
> +      @department = Department.find(params[:faculty_id])
Сделай тут поиск не среди всех, а среди департаментов факультета

2022-02-11 14:56 UTC, IvanChibisov commented on app/controllers/faculties_controller.rb
> +  def show
Сокращенный формат сделай

2022-02-11 14:56 UTC, IvanChibisov commented on app/controllers/faculties_controller.rb
> +      format.json { head :no_content }
Сделай обработку ошибки, если не удалилось

2022-02-11 14:56 UTC, IvanChibisov commented on app/controllers/faculties_controller.rb
> +
Удали пустую строку

2022-02-11 14:56 UTC, IvanChibisov commented on app/controllers/departments_controller.rb
> +      format.json { head :no_content }
Тут с выравниваем норм всё?

2022-02-14 13:15 UTC, IvanChibisov requested changes

2022-02-14 13:15 UTC, IvanChibisov commented on app/controllers/departments_controller.rb
> +      @department = @faculty.departments
Тут же нет find

2022-02-14 17:13 UTC, pejath commented on app/controllers/departments_controller.rb
> +      @department = @faculty.departments
а в чем проблема данного решения?

2022-02-14 17:17 UTC, IvanChibisov commented on app/controllers/departments_controller.rb
> +      @department = @faculty.departments
Ты же получаешь не один department а все departments, которые принадлежат факультету

2022-02-15 19:29 UTC, merged